# Generated by Django 5.2.1 on 2026-03-17 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_rsvp'),
        ),
    ]
